# Spring Boot Application Name
spring.application.name=Basic-SpringBoot

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/basic-spring-boot
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.main.allow-bean-definition-overriding=true

# Enable camelCase mapping
mybatis.configuration.map-underscore-to-camel-case=true